### ISSUE TITLE
Feature request: uploading compressed files/folders

### ISSUE THREAD

**Issue by johannesu** [slicebox/slicebox#106]
Having the ability to upload compressed files would greatly reduce the upload time (especially for segmentation files).

I believe it also possible to compress the files client side before uploading them with something like:
http://stuk.github.io/jszip/

**Comment by KarlSjostrand** [comment]
We agree that many types of DICOM files compress nicely and that this would speed up imports. The box-to-box transfer protocol used by slicebox includes compression but uploading does not. 

We are currently working on a new pipeline for handling DICOM data in slicebox. As part of this, we plan to support the deflated DICOM transfer syntax (1.2.840.10008.1.2.1.99) which is the standard Explicit VR Little Endian transfer syntax with a deflated dataset. As soon as this feature is out, you can migrate your segmentation datasets to this transfer syntax which would mean that data is permanently compressed, not just during upload.

Would this meet your requirements?

**Comment by johannesu** [comment]
Yes, thank you.
