### ISSUE TITLE
Missing deb package on bintray?

### ISSUE THREAD

**Issue by ghisvail** [slicebox/slicebox#269]
The following [instructions](https://github.com/slicebox/slicebox/wiki/Installing-a-Public-Slicebox#linux-debian---installation-and-configuration) mention the availability of a `deb` package on [bintray](https://bintray.com/slicebox/slicebox/installers/v1.4.1), but the listing only contains a `zip` archive and a `rpm` package.

**Comment by KarlSjostrand** [comment]
Debian package uploaded for version 1.4.1. Thanks for the heads-up!
