### ISSUE TITLE
Unhelpful failure message on import of a dataset with an unsupported transfer syntax

### ISSUE THREAD

**Issue by ghisvail** [slicebox/slicebox#276]
Trying to import a dataset with an unsupported transfer syntax yield the following error in the log:
```
2018-04-23 13:24:43,549 ERROR (akka://slicebox) - Import: AbruptIOTerminationException during import of F000001: failure.getMessage
```

Version `1.4.1` gave a more explicit failure message pointing at the root cause of the issue.

**Comment by KarlSjostrand** [comment]
Fixed by #274
