### ISSUE TITLE
FrameOfReference in ReverseAnonymization

### ISSUE THREAD

**Issue by rickardcronholm** [slicebox/slicebox#290]
Currently the reverse anonymization of the FrameOfReferenceUID is tied to `keypart.hasSeriesInfo`. I argue that this is incorrect as multiple Seires can (and often do) share the same FrameOfReference. See section C.7.4.1 in DICOM PS3.3 2016e - Information Object Definitions [http://dicom.nema.org/medical/dicom/2016e/output/chtml/part03/sect_C.7.4.html](url)

> Table C.7-6 specifies the Attributes necessary to uniquely identify a frame of reference that ensures the spatial relationship of Images within a Series. It also allows Images across multiple Series to share the same Frame Of Reference.

My suggestion is to add `hasFrameInfo` to `PartialAnonymizationKeyPart`

**Comment by rickardcronholm** [comment]
#291

**Comment by KarlSjostrand** [comment]
My understanding of how this works, specifically that series are only related within a study, comes from C.7.4.1.1.1. Quote: _The Frame of Reference UID (0020,0052) shall be used to uniquely identify a Frame of Reference for a Series. Each Series shall have a single Frame of Reference UID. However, multiple Series within a Study may share a Frame of Reference UID. All images in a Series that share the same Frame of Reference UID shall be spatially related to each other._ The _within a study_ is what led me in this direction. Have you seen examples of series from different studies being spatially related?

**Comment by KarlSjostrand** [comment]
That explains it! I was on the wrong track, thanks for clarifying. I think the DICOM model here http://dicom.nema.org/medical/dicom/current/output/html/part03.html#figure_7-1a supports what you are saying, Equipment and Frame of Reference are separate objects.

**Comment by KarlSjostrand** [comment]
Fixed in 2.0
