### ISSUE TITLE
Some character sets not displayed correctly

### ISSUE THREAD

**Issue by fredrik-exini** [slicebox/slicebox#90]
Dicom objects with patient name encoded in some character sets, e.g. Arabic, Greek and Japanese, are not displayed correctly in the patients table. Question marks are shown instead characters of the specific character set. If opening a series and inspecting the DICOM tags the patient name is displayed correctly.
[nmarab-slim.zip](https://github.com/slicebox/slicebox/files/739000/nmarab-slim.zip)

**Comment by KarlSjostrand** [comment]
This seems to work when using a H2 database. The problem arises when using MySQL databases.
